[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[colors.primary]
background = "0x1e1e2e"
foreground = "0xf2e9e1"

[window]
opacity = 0.7
padding.x = 0
padding.y = 0
decorations = "Buttonless"
blur = true
startup_mode = "Maximized" # Other options: "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"
option_as_alt = "Both"
dynamic_title = false

[font]
normal.family = "JetBrainsMono Nerd Font" # Other options: "FiraCode Nerd Font", "MesloLG Nerd Font"
size = 15

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux new"]

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
# Ctrl + →
key = "Right"
mods = "Option"
chars = "\u001b[1;5C"

[[keyboard.bindings]]
# Ctrl + ←
key = "Left"
mods = "Option"
chars = "\u001b[1;5D"

