# General GUI Settings
gui:
  showIcons: false
  theme:
    activeBorderColor:
      # - "#cba6f7" # lavender
      - "#9399b2" # overlay2
      - bold
    inactiveBorderColor:
      # - "#45475a" # surface1
      # - "#cba6f7" # lavender (same as active, no bold)
      - "#7f849c" # overlay1
    selectedLineBgColor:
      # - "#45475a" # surface1
      - "#6c7086" # overlay0
    cherryPickedCommitBgColor:
      - "#a6e3a1" # green
    cherryPickedCommitFgColor:
      - "#11111b" # base
    markedBaseCommitFgColor:
      - "#fab387" # peach
    markedBaseCommitBgColor:
      - "#11111b" # base
    unstagedChangesColor:
      - "#f38ba8" # red
    defaultFgColor:
      # - "#cdd6f4" # text
      - "#9399b2" # overlay2
    inactiveViewSelectedLineBgColor:
      - "#cdd6f4" # surface1
      # - "#9399b2" # overlay2
    optionsTextColor:
      # - "#cdd6f4"
      - "#9399b2" # overlay2
    searchingActiveBorderColor:
      - "#f38ba8" # pink accent for search
# Git Settings
git:
  pagers:
    - colorArg: always
      pager: delta --paging=never
# Services Configuration
services:
  "github.com": "github:github.com"
  "gitlab.com": "gitlab:gitlab.com"
  "bitbucket.org": "bitbucket:bitbucket.org"
